<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!--Modify This For Each Project-->
    <ProjectName>StrategistSubclasses</ProjectName>
  
    <AssetsFolder>$(ProjectName)Assets</AssetsFolder>
  </PropertyGroup>
  
  <!-- Asset Folders -->
  <ItemGroup>
    <Assets Include="$(AssetsFolder)\**\*.*"/>
  </ItemGroup>
  
  <Target Name="CopyToGameModsFolder" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(DawnsburyInstall)\CustomMods"/>
    <Copy SourceFiles="@(Assets)" DestinationFolder="$(DawnsburyInstall)\CustomMods\$(AssetsFolder)\%(RecursiveDir)"/>
  
    <Message Text="Copied to game mod folder." />
  </Target>
  
  <Target Name="CopyToWorkshopUploadable" AfterTargets="Build" Condition=" '$(Configuration)'=='Release' ">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(WorkshopExport)\$(ProjectName)\CustomModsV3"/>
    <Copy SourceFiles="OGL copyright notice.html" DestinationFolder="$(WorkshopExport)\$(ProjectName)" ContinueOnError="true"/>
    <Copy SourceFiles="optional-dependencies.txt" DestinationFolder="$(WorkshopExport)\$(ProjectName)" ContinueOnError="true"/>
    <Copy SourceFiles="@(Assets)" DestinationFolder="$(WorkshopExport)\$(ProjectName)\CustomModsV3\$(AssetsFolder)\%(RecursiveDir)"/>
  
    <Message Text="Copied to mod publishing folder." />
  </Target>

</Project>

