<Project Sdk="Microsoft.NET.Sdk">

  <!-- See the template Directory.Builds.props for additional information -->
  
  <PropertyGroup>
    <!--Modify This For Each Project-->
    <ProjectName>MoreShields</ProjectName>
  
    <AssetsFolder>$(ProjectName)Assets</AssetsFolder>
  </PropertyGroup>
  
  <ItemGroup>
    <!--<Reference Include="Dawnsbury.Mods.DawnniExpanded">
      <HintPath>$(WorkshopInstalls)\3163146733\CustomMods\Dawnsbury.Mods.DawnniExpanded.dll</HintPath>
    </Reference>-->
    <!--<Reference Include="Dawnsbury.Mods.MoreShields">
        <HintPath>..\More Shields\[Workshop Files]\[Export]\CustomModsV3\Dawnsbury.Mods.MoreShields.dll</HintPath>
    </Reference>-->
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
  </ItemGroup>
  
  <!-- Asset Folders -->
  <ItemGroup>
    <Assets Include="$(AssetsFolder)\**\*.*"/>
  </ItemGroup>
  
  <Target Name="CopyToGameModsFolder" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(DawnsburyInstall)\CustomMods"/>
    <Copy SourceFiles="@(Assets)" DestinationFolder="$(DawnsburyInstall)\CustomMods\$(AssetsFolder)\%(RecursiveDir)"/>
  
    <Message Text="Copied to game mod folder." />
  </Target>
  
  <Target Name="CopyToWorkshopUploadable" AfterTargets="Build" Condition=" '$(Configuration)'=='Release' ">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(WorkshopExport)\$(ProjectName)\CustomModsV3"/>
    <Copy SourceFiles="0Harmony.dll" DestinationFolder="$(WorkshopExport)\$(ProjectName)\CustomModsV3"/>
    <Copy SourceFiles="OGL copyright notice.html" DestinationFolder="$(WorkshopExport)\$(ProjectName)" ContinueOnError="true"/>
    <Copy SourceFiles="@(Assets)" DestinationFolder="$(WorkshopExport)\$(ProjectName)\CustomModsV3\$(AssetsFolder)\%(RecursiveDir)"/>
  
    <Message Text="Copied to mod publishing folder." />
  </Target>

</Project>

