<Project Sdk="Microsoft.NET.Sdk">

  <!-- See the template Directory.Builds.props for additional information -->

  <PropertyGroup>
    <!--Modify This For Each Project-->
    <ProjectName>SlayerClass</ProjectName>

    <AssetsFolder>$(ProjectName)Assets</AssetsFolder>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SpiritDamage.dll">
      <HintPath>$(WorkshopInstalls)\3577287156\CustomMods\SpiritDamage.dll</HintPath>
    </Reference>
    <Reference Include="New_Skill_Feats_and_Items">
      <HintPath>$(WorkshopInstalls)\3518902782\CustomMods\New Skill Feats and Items.dll</HintPath>
    </Reference>
    <Reference Include="Dawnsbury.Mods.LoresAndWeaknesses.dll"> <!--3710730920-->
      <HintPath>..\[Exports]\LoresAndWeaknesses\CustomModsV3\Dawnsbury.Mods.LoresAndWeaknesses.dll</HintPath>
    </Reference>
    <Reference Include="Dawnsbury.Mods.MoreShields.dll"> <!--3538575665-->
      <HintPath>..\[Exports]\MoreShields\CustomModsV3\Dawnsbury.Mods.MoreShields.dll</HintPath>
    </Reference>
  </ItemGroup>

  <!-- Asset Folders -->
  <ItemGroup>
    <Assets Include="$(AssetsFolder)\**\*.*"/>
  </ItemGroup>
  
  <Target Name="CopyToGameModsFolder" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(DawnsburyInstall)\CustomMods"/>
    <Copy SourceFiles="@(Assets)" DestinationFolder="$(DawnsburyInstall)\CustomMods\$(AssetsFolder)\%(RecursiveDir)"/>
    
    <Message Text="Copied to game mod folder." />
  </Target>
  
  <Target Name="CopyToWorkshopUploadable" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(WorkshopExport)\$(ProjectName)\CustomModsV3"/>
    <Copy SourceFiles="ORC copyright notice.html" DestinationFolder="$(WorkshopExport)\$(ProjectName)" ContinueOnError="true"/>
    <Copy SourceFiles="optional-dependencies.txt" DestinationFolder="$(WorkshopExport)\$(ProjectName)" ContinueOnError="true"/>
    <Copy SourceFiles="@(Assets)" DestinationFolder="$(WorkshopExport)\$(ProjectName)\CustomModsV3\$(AssetsFolder)\%(RecursiveDir)"/>

    <Message Text="Copied to mod publishing folder." />
  </Target>
  
</Project>
