<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platform>x64</Platform>
    <PlatformTarget>x64</PlatformTarget>
    <NoWarn>1998;NETSDK1206;NU1901;NU1902;NU1903;NU1904</NoWarn>
    <WarningsAsErrors>0618</WarningsAsErrors>
    <!--<DawnsburyInstall>Set inside of Directory.Build.props</DawnsburyInstall>-->
    <!--<WorkshopInstalls>Set inside of Directory.Build.props</WorkshopInstalls>-->
    <WorkshopExport>[Workshop Files]\[Export]</WorkshopExport>
    <AssetsFolder>SlayerClassAssets</AssetsFolder>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Common">
      <HintPath>$(DawnsburyInstall)\Data\Common.dll</HintPath>
    </Reference>
    <Reference Include="Dawnsbury Days">
      <HintPath>$(DawnsburyInstall)\Data\Dawnsbury Days.dll</HintPath>
    </Reference>
    <Reference Include="MonoGame.Framework">
      <HintPath>$(DawnsburyInstall)\Data\MonoGame.Framework.dll</HintPath>
    </Reference>
    <Reference Include="SpiritDamage.dll">
      <HintPath>$(WorkshopInstalls)\3577287156\CustomMods\SpiritDamage.dll</HintPath>
    </Reference>
    <Reference Include="New_Skill_Feats_and_Items">
      <HintPath>$(WorkshopInstalls)\3518902782\CustomMods\New Skill Feats and Items.dll</HintPath>
    </Reference>
    <Reference Include="Dawnsbury.Mods.LoresAndWeaknesses.dll"> <!--3710730920-->
      <HintPath>..\Lores and Weaknesses\[Workshop Files]\[Export]\CustomModsV3\Dawnsbury.Mods.LoresAndWeaknesses.dll</HintPath>
    </Reference>
    <Reference Include="Dawnsbury.Mods.MoreShields.dll"> <!--3538575665-->
      <HintPath>..\More Shields\[Workshop Files]\[Export]\CustomModsV3\Dawnsbury.Mods.MoreShields.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <Target Name="CopyToGameModsFolder" AfterTargets="Build">
    <ItemGroup>
      <Assets Include="$(AssetsFolder)\**\*.*"/>
    </ItemGroup>
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(DawnsburyInstall)\CustomMods"/>
    <Copy SourceFiles="@(Assets)" DestinationFolder="$(DawnsburyInstall)\CustomMods\$(AssetsFolder)\%(RecursiveDir)"/>
  </Target>
  
  <Target Name="CopyToWorkshopUploadable" AfterTargets="Build">
    <ItemGroup>
      <Assets Include="$(AssetsFolder)\**\*.*"/>
    </ItemGroup>
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(WorkshopExport)\CustomModsV3"/>
    <Copy SourceFiles="ORC copyright notice.html" DestinationFolder="$(WorkshopExport)" ContinueOnError="true"/>
	<Copy SourceFiles="optional-dependencies.txt" DestinationFolder="$(WorkshopExport)" ContinueOnError="true"/>
    <Copy SourceFiles="@(Assets)" DestinationFolder="$(WorkshopExport)\CustomModsV3\$(AssetsFolder)\%(RecursiveDir)"/>
  </Target>
  
</Project>
