<Project Sdk="Microsoft.NET.Sdk">
  
  <!-- See the template Directory.Builds.props for additional information -->
  
  <PropertyGroup>
    <!--Modify This For Each Project-->
    <ProjectName>KholoAncestry</ProjectName>
  
    <AssetsFolder>$(ProjectName)Assets</AssetsFolder>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Dawnsbury.Mods.LoresAndWeaknesses">
        <HintPath>..\[Exports]\LoresAndWeaknesses\CustomModsV3\Dawnsbury.Mods.LoresAndWeaknesses.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <!-- Asset Folders -->
  <ItemGroup>
    <Assets Include="$(AssetsFolder)\**\*.*"/>
    <!--<Tokens1 Include="$(Tokens1Folder)\**\*.*"/>-->
    <Tokens2 Include="$(Tokens2Folder)\**\*.*"/>
  </ItemGroup>
  
  <Target Name="CopyToGameModsFolder" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(DawnsburyInstall)\CustomMods"/>
    <Copy SourceFiles="@(Assets)" DestinationFolder="$(DawnsburyInstall)\CustomMods\$(AssetsFolder)\%(RecursiveDir)"/>
    <!--<Copy SourceFiles="@(Tokens1)" DestinationFolder="$(DawnsburyInstall)\$(Tokens1Folder)\%(RecursiveDir)"/>-->
    <Copy SourceFiles="@(Tokens2)" DestinationFolder="$(DawnsburyInstall)\$(Tokens2Folder)\%(RecursiveDir)"/>
  
    <Message Text="Copied to game mod folder." />
  </Target>
  
  <Target Name="CopyToWorkshopUploadable" AfterTargets="Build" Condition=" '$(Configuration)'=='Release' ">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(WorkshopExport)\$(ProjectName)\CustomModsV3"/>
    <Copy SourceFiles="ORC copyright notice.html" DestinationFolder="$(WorkshopExport)\$(ProjectName)" ContinueOnError="true"/>
    <Copy SourceFiles="optional-dependencies.txt" DestinationFolder="$(WorkshopExport)\$(ProjectName)" ContinueOnError="true"/>
    <Copy SourceFiles="@(Assets)" DestinationFolder="$(WorkshopExport)\$(ProjectName)\CustomModsV3\$(AssetsFolder)\%(RecursiveDir)"/>
    <!--<Copy SourceFiles="@(Tokens1)" DestinationFolder="$(WorkshopExport)\$(ProjectName)\$(Tokens1Folder)\%(RecursiveDir)"/>-->
    <Copy SourceFiles="@(Tokens2)" DestinationFolder="$(WorkshopExport)\$(ProjectName)\$(Tokens2Folder)\%(RecursiveDir)"/>
  
    <Message Text="Copied to mod publishing folder." />
  </Target>
  
</Project>