using Dawnsbury.Core;
using Dawnsbury.Core.CharacterBuilder.Feats;
using Dawnsbury.Core.CharacterBuilder.FeatsDb;
using Dawnsbury.Core.CharacterBuilder.FeatsDb.Champion;
using Dawnsbury.Core.CharacterBuilder.Spellcasting;
using Dawnsbury.Core.CombatActions;
using Dawnsbury.Core.Creatures;
using Dawnsbury.Core.Mechanics;
using Dawnsbury.Core.Mechanics.Enumerations;
using Dawnsbury.Display.Illustrations;
using Dawnsbury.Modding;

namespace Dawnsbury.Mods.MoreDedications;

public static class ModData
{
    public const string ID_PREPEND = "MoreDedications.";

    public static Trait ModTrait;
    
    /// <summary>
    /// Loads all mod data. This should typically be called by a mod before anything else.
    /// </summary>
    /// <para>
    /// When registering mod data, certain data must be called through the execution of lines of code, rather than assigned in their initialization. The Initializer skips these data until they're first called, which can result in errors due to out of order registration calls (especially when another mod isn't using <see cref="ModManager.TryParse"/>).
    /// </para>
    /// <para>The following data forms are typically safe due to the way Dawnsbury Days loads mods (or because their initialization nearly always gets called before errors could arise): <see cref="FeatName"/>, <see cref="Illustration"/>, <see cref="Trait"/>, <see cref="SfxNames"/>, <see cref="SpellId"/>. Tooltips from <see cref="ModManager.RegisterInlineTooltip(string, string)"/> likely aren't safe to assign as part of the initializer, but they typically shouldn't be shared between mods either.
    /// </para>
    /// <para>
    /// In general, trigger the initializer by separating declaration and assignment for the following data forms:
    /// <list type="bullet">
    /// <item>All other enums (e.g. <see cref="ActionId"/>, <see cref="QEffectId"/>)</item>
    /// <item>Mod settings registered with <see cref="ModManager.RegisterBooleanSettingsOption"/></item>
    /// </list>
    /// </para>
    public static void LoadData()
    {
        ModTrait = ModManager.ModBeingLoadedTrait!.Value; // Known not null at this stage
        ActionIds.Initialize();
        // Deferred until later. Dedications don't have an assigned value until the end.
        //FeatNames.ReplaceOldFeatNames();
        QEffectIds.Initialize();
    }

    public static class ActionIds
    {
        public static ActionId TigerSlash;
        
        public static void Initialize()
        {
            TigerSlash = ModManager.SafelyRegisterEnumMember<ActionId>("TigerSlash");
        }
    }

    public static class CommonRequirements
    {
        public static Func<Creature, string?> StanceRestriction(QEffectId stanceId)
        {
            return self =>
            {
                if (self.HasEffect(stanceId))
                    return "You're already in this stance.";
                return null;
            };
        }
    }
    
    public static class FeatNames
    {
        // In the early days of this mod, there were attempts to avoid
        // mod conflicts by using unique strings. There are better
        // techniques, since this mod first began, to avoid conflicts
        // generated by making new feats:
        // - If a mod attempts to register a base game FeatName and add a Feat, the base game takes precedence (no exceptions thrown).
        // - ModManager.TryParse, and the functions I've built that use such functions in a shortcut manner, make this more reliable.
        // - ModManager.RegisterFeatNameReplacement allows me to switch to using base game-like FeatName strings without breaking character sheets.
        public static void ReplaceOldFeatNames()
        {
            #region Mauler

            ReplaceModDedWithModDed(
                Traits.Mauler,
                MaulerDedication);
            // Replace "KnockdownForMoreDedications.Mauler" with "KnockdownForMauler".
            ReplaceBaseForWithModFor(
                FeatName.Knockdown,
                Traits.Mauler,
                KnockdownForMauler);
            ReplaceBaseForWithModFor(
                FeatName.PowerAttack,
                Traits.Mauler,
                PowerAttackForMauler);
            ReplaceModWithMod(
                "MoreDedications.Archetype.Mauler.ClearTheWay",
                ClearTheWay);
            ReplaceModWithMod(
                "MoreDedications.Archetype.Mauler.ShovingSweep",
                ShovingSweep);

            #endregion

            #region Archer
            
            ReplaceModClassWithModClass(
                "MoreDedications.Class.Fighter.PartingShot",
                PartingShot);
            ReplaceModClassForWithModClassFor(
                "MoreDedications.Class.Fighter.PartingShot",
                Traits.Mauler,
                PartingShotForArcher);

            #endregion

            #region Bastion

            ReplaceModDedWithModDed(
                Traits.Bastion,
                BastionDedication);
            ReplaceBaseForWithModFor(
                Champion.AgileShieldGripFeatName,
                Traits.Bastion,
                AgileShieldGripForBastion);
            ReplaceModWithMod(
                "MoreDedications.Archetype.Bastion.DisarmingBlock",
                DisarmingBlock);
            ReplaceModWithMod(
                "MoreDedications.Archetype.Bastion.NimbleShieldHand",
                NimbleShieldHand);
            ReplaceModClassWithModClass(
                "MoreDedications.Class.Fighter.ShieldedStride",
                ShieldedStride);
            ReplaceModClassForWithModClassFor(
                "MoreDedications.Class.Fighter.ShieldedStride",
                Traits.Bastion,
                ShieldedStrideForBastion);
            ReplaceModClassWithModClass(
                "MoreDedications.Class.Fighter.ReflexiveShield",
                ReflexiveShield);
            ReplaceModClassForWithModClassFor(
                "MoreDedications.Class.Fighter.ReflexiveShield",
                Traits.Bastion,
                ReflexiveShieldForBastion);
            ReplaceBaseForWithModFor(
                FeatName.ShieldWarden,
                Traits.Bastion,
                ShieldWardenForBastion);

            #endregion

            #region Martial Artist

            ReplaceModDedWithBaseDed(Trait.MartialArtist);
            ReplaceModWithMod(
                "MoreDedications.Archetype.MartialArtist.PowderPunchStance",
                PowderPunchStance);
            ReplaceBaseForWithBaseFor(
                FeatName.BrawlingFocus,
                Trait.MartialArtist);
            ReplaceBaseForWithBaseFor(
                FeatName.CraneStance,
                Trait.MartialArtist);
            ReplaceBaseForWithBaseFor(
                FeatName.DragonStance,
                Trait.MartialArtist);
            ReplaceBaseForWithBaseFor(
                FeatName.GorillaStance,
                Trait.MartialArtist);
            ReplaceBaseForWithBaseFor(
                FeatName.MountainStance,
                Trait.MartialArtist);
            ReplaceBaseForWithBaseFor(
                FeatName.WolfStance,
                Trait.MartialArtist);
            ReplaceBaseForWithBaseFor(
                FeatName.CraneFlutter,
                Trait.MartialArtist);
            ReplaceBaseForWithBaseFor(
                FeatName.DragonRoar,
                Trait.MartialArtist);
            ReplaceBaseForWithBaseFor(
                FeatName.GorillaPound,
                Trait.MartialArtist);
            ReplaceBaseForWithBaseFor(
                FeatName.MountainStronghold,
                Trait.MartialArtist);
            ReplaceBaseForWithBaseFor(
                FeatName.WolfDrag,
                Trait.MartialArtist);
            ReplaceBaseForWithBaseFor(
                StumblingStance,
                Trait.MartialArtist);
            ReplaceBaseForWithBaseFor(
                TigerStance,
                Trait.MartialArtist);
            ReplaceModWithMod(
                "MoreDedications.Archetype.MartialArtist.FollowUpStrike",
                FeatName.FollowUpStrike);
            ReplaceModWithMod(
                "MoreDedications.Archetype.MartialArtist.ThunderClap",
                ThunderClap);
            ReplaceBaseForWithBaseFor(
                FeatName.GrievousBlow,
                Trait.MartialArtist);
            ReplaceBaseForWithBaseFor(
                StumblingFeint,
                Trait.MartialArtist);
            ReplaceBaseForWithBaseFor(
                TigerSlash,
                Trait.MartialArtist);

            #endregion

            #region Marshal

            ReplaceModDedWithModDed(
                Traits.Marshal,
                MarshalDedication);
            ReplaceModWithMod(
                "MoreDedications.Archetype.Marshal.DreadMarshalStance",
                DreadMarshalStance);
            ReplaceModWithMod(
                "MoreDedications.Archetype.Marshal.InspiringMarshalStance",
                InspiringMarshalStance);
            ReplaceModWithMod(
                "MoreDedications.Archetype.Marshal.SteelYourself",
                SteelYourself);
            ReplaceModWithMod(
                "MoreDedications.Archetype.Marshal.RallyingCharge",
                RallyingCharge);
            ReplaceBaseForWithModFor(
                FeatName.AttackOfOpportunity,
                Traits.Marshal,
                AttackOfOpportunityForMarshal);
            ReplaceModWithMod(
                "MoreDedications.Archetype.Marshal.BackToBack",
                BackToBack);
            ReplaceModWithMod(
                "MoreDedications.Archetype.Marshal.ToBattle",
                ToBattle);

            #endregion

            #region Blessed One

            ReplaceModDedWithModDed(
                Traits.BlessedOne,
                BastionDedication);
            ReplaceModWithMod(
                "MoreDedications.Archetype.BlessedOne.BlessedSacrifice",
                BlessedSacrifice);
            ReplaceBaseForWithModFor(
                Champion.AcceleratingTouchFeatName,
                Traits.BlessedOne,
                AcceleratingTouchForBlessedOne);

            #endregion

            #region Scout

            ReplaceModWithMod(
                "MoreDedications.Archetype.Scout.ScoutsCharge",
                ScoutsCharge);
            // Skip TerrainScout which was never implemented despite registration. //
            ReplaceModWithMod(
                "MoreDedications.Archetype.Scout.FleetingShadow",
                FleetingShadow);
            ReplaceModWithMod(
                "MoreDedications.Archetype.Scout.ScoutsSpeed",
                ScoutsSpeed);
            // Skip ScoutsPounce which was never implemented despite registration. //

            #endregion

            #region Assassin

            ReplaceModDedWithModDed(
                Traits.Assassin,
                AssassinDedication);
            ReplaceModWithMod(
                "MoreDedications.Archetype.Assassin.ExpertBackstabber",
                ExpertBackstabber);
            ReplaceBaseForWithModFor(
                FeatName.PoisonResistanceDruid,
                Traits.Assassin,
                PoisonResistanceForAssassin);
            ReplaceModWithMod(
                "MoreDedications.Archetype.Assassin.SurpriseAttack",
                SurpriseAttack);
            ReplaceBaseForWithModFor(
                PoisonWeapon,
                Traits.Assassin,
                PoisonWeaponForAssassin);
            ReplaceBaseForWithModFor(
                FeatName.SneakAttacker,
                Traits.Assassin,
                SneakAttackerForAssassin);
            ReplaceBaseForWithModFor(
                ImprovedPoisonWeapon,
                Traits.Assassin,
                ImprovedPoisonWeaponForAssassin);

            #endregion

            #region Dual-Weapon Warrior

            ReplaceModDedWithModDed(
                Traits.DualWeaponWarrior,
                DualWeaponWarriorDedication);
            ReplaceModWithMod(
                "MoreDedications.Archetype.DualWeaponWarrior.DualThrower",
                DualThrower);
            ReplaceModWithMod(
                "MoreDedications.Archetype.DualWeaponWarrior.FlensingSlice",
                FlensingSlice);

            #endregion

            // Medic does not need to be updated.

            #region Familiar Master

            ReplaceModDedWithModDed(
                Traits.FamiliarMaster,
                FamiliarMasterDedication);
            ReplaceBaseForWithModFor(
                FeatName.DawnsburyEnhancedFamiliar,
                Traits.FamiliarMaster,
                EnhancedFamiliarForFamiliarMaster);
            ReplaceModWithMod(
                "MoreDedications.Archetype.FamiliarMaster.OverloadFamiliar",
                OverloadFamiliar);
            ReplaceModWithMod(
                "MoreDedications.Archetype.FamiliarMaster.FastCommand",
                FastCommand);
            ReplaceModWithMod(
                "MoreDedications.Archetype.FamiliarMaster.MutableFamiliar",
                MutableFamiliar);
            ReplaceModWithMod(
                "MoreDedications.Archetype.FamiliarMaster.IncredibleFamiliar",
                IncredibleFamiliar);

            #endregion

            #region Wrestler

            ReplaceModWithMod(
                "MoreDedications.Archetype.Wrestler.ElbowBreaker",
                ElbowBreaker);

            #endregion

            #region Local Functions

            // I removed ID_PREPEND from all FeatNames and Traits.
            // As a result, I need to replace:
            
            // - Modded dedications to modded
            // ("MoreDedications.MaulerDedication" -> "MaulerDedication")
            void ReplaceModDedWithModDed(Trait archetype, FeatName newDedication)
            {
                string oldTechnical = ID_PREPEND + archetype.ToStringOrTechnical() + "Dedication";
                ModManager.RegisterFeatNameReplacement(oldTechnical, newDedication);
            }

            // - Modded dedications to base
            // ("MoreDedications.MartialArtist" -> "MartialArtistDedication")
            void ReplaceModDedWithBaseDed(Trait archetype)
            {
                string traitTech = archetype.ToStringOrTechnical();
                string oldTechnical = ID_PREPEND + traitTech + "Dedication";
                if (AllFeats.GetFeatByFeatNameOrStringOptional(null, traitTech + "Dedication") is { } newDed)
                    ModManager.RegisterFeatNameReplacement(oldTechnical, newDed.FeatName);
            }

            // - Modded feats to modded feats
            // ("MoreDedications.Archetype.Mauler.ClearTheWay" -> "ClearTheWay")
            void ReplaceModWithMod(string oldMod, FeatName newMod)
            {
                ModManager.RegisterFeatNameReplacement(oldMod, newMod);
            }
            
            // - Modded class feats
            // ("MoreDedications.Class.Fighter.ShieldedStride" -> "ShieldedStride")
            void ReplaceModClassWithModClass(string oldClass, FeatName newClass)
            {
                ModManager.RegisterFeatNameReplacement(oldClass, newClass);
            }
            
            // - Modded feats for modded archetypes
            // ("MoreDedications.Class.Fighter.ShieldedStride" + "ForArchetype" + "MoreDedications.Mauler" -> "ShieldedStrideForArchetypeMauler")
            void ReplaceModClassForWithModClassFor(string oldMod, Trait forArchetype, FeatName newMod)
            {
                ModManager.RegisterFeatNameReplacement(
                    oldMod + "ForArchetype" + ID_PREPEND + forArchetype.ToStringOrTechnical(),
                    newMod);
            }
            
            // - Base feats for modded archetypes
            // (FeatName.Knockdown + "ForArchetype" + "MoreDedications.Mauler" -> "KnockdownForArchetypeMauler")
            void ReplaceBaseForWithModFor(FeatName baseFeat, Trait forArchetype, FeatName newMod)
            {
                ModManager.RegisterFeatNameReplacement(
                    baseFeat.ToStringOrTechnical() + "ForArchetype" + ID_PREPEND + forArchetype.ToStringOrTechnical(),
                    newMod);
            }
            
            // - Base game feats for base game archetypes
            // - Modded feats with base-like names for base game archetypes
            // (FeatName.BrawlingFocus + "ForArchetype" + "MoreDedications.MartialArtist" -> "BrawlingFocusForArchetypeMartialArtist")
            void ReplaceBaseForWithBaseFor(FeatName baseFeat, Trait forArchetype)
            {
                string baseTech = baseFeat.ToStringOrTechnical();
                string traitTech = forArchetype.ToStringOrTechnical();
                string oldTech = baseTech + "ForArchetype" + ID_PREPEND + traitTech;
                string newTech =  baseTech + "ForArchetype" + traitTech;
                if (AllFeats.GetFeatByFeatNameOrStringOptional(null, newTech) is { } newFeat)
                    ModManager.RegisterFeatNameReplacement(
                        oldTech,
                        newFeat.FeatName);
            }

            #endregion
        }
        
        #region Mauler

        public static FeatName MaulerDedication;
        public static FeatName KnockdownForMauler;
        public static FeatName PowerAttackForMauler;
        public static readonly FeatName ClearTheWay = ModManager.SafelyRegisterEnumMember<FeatName>(
            "ClearTheWay",
            ["Clear the Way"]);
        public static readonly FeatName ShovingSweep = ModManager.SafelyRegisterEnumMember<FeatName>(
            "ShovingSweep",
            ["Shoving Sweep"]);
        public static FeatName ImprovedKnockdownForMauler;
        
        #endregion
        
        #region Archer

        public static FeatName QuickDrawForArcher;
        public static readonly FeatName PartingShot = ModManager.SafelyRegisterEnumMember<FeatName>(
            "PartingShot",
            ["Parting Shot"]);
        public static FeatName PartingShotForArcher;
        
        #endregion
        
        #region Bastion

        public static FeatName BastionDedication;
        public static FeatName AgileShieldGripForBastion;
        public static readonly FeatName DisarmingBlock = ModManager.SafelyRegisterEnumMember<FeatName>(
            "DisarmingBlock",
            ["Disarming Block"]);
        public static readonly FeatName NimbleShieldHand = ModManager.SafelyRegisterEnumMember<FeatName>(
            "NimbleShieldHand",
            ["Nimble Shield Hand"]);
        public static readonly FeatName ShieldedStride = ModManager.SafelyRegisterEnumMember<FeatName>(
            "ShieldedStride",
            ["Shielded Stride"]);
        public static FeatName ShieldedStrideForBastion;
        public static readonly FeatName ReflexiveShield = ModManager.SafelyRegisterEnumMember<FeatName>(
            "ReflexiveShield",
            ["Reflexive Shield"]);
        public static FeatName ReflexiveShieldForBastion;
        public static FeatName ShieldWardenForBastion;
        
        #endregion
        
        #region Martial Artist
        
        public static readonly FeatName PowderPunchStance = ModManager.SafelyRegisterEnumMember<FeatName>(
            "PowderPunchStance",
            ["Powder Punch Stance"]);
        public static readonly FeatName StumblingStance = ModManager.SafelyRegisterEnumMember<FeatName>(
            "StumblingStance",
            ["Stumbling Stance"]);
        public static readonly FeatName TigerStance = ModManager.SafelyRegisterEnumMember<FeatName>(
            "TigerStance",
            ["Tiger Stance"]);
        public static readonly FeatName ThunderClap = ModManager.SafelyRegisterEnumMember<FeatName>(
            "ThunderClap",
            ["Thunder Clap"]);
        public static readonly FeatName StumblingFeint = ModManager.SafelyRegisterEnumMember<FeatName>(
            "StumblingFeint",
            ["Stumbling Feint"]);
        public static readonly FeatName TigerSlash = ModManager.SafelyRegisterEnumMember<FeatName>(
            "TigerSlash",
            ["Tiger Slash"]);
        
        #endregion
        
        #region Marshal

        public static FeatName MarshalDedication;
        public static readonly FeatName DreadMarshalStance = ModManager.SafelyRegisterEnumMember<FeatName>(
            "DreadMarshalStance",
            ["Dread Marshal Stance"]);
        public static readonly FeatName InspiringMarshalStance = ModManager.SafelyRegisterEnumMember<FeatName>(
            "InspiringMarshalStance",
            ["Inspiring Marshal Stance"]);
        public static readonly FeatName SteelYourself = ModManager.SafelyRegisterEnumMember<FeatName>(
            "SteelYourself",
            ["Steel Yourself!"]);
        public static readonly FeatName RallyingCharge = ModManager.SafelyRegisterEnumMember<FeatName>(
            "RallyingCharge",
            ["Rallying Charge"]);
        public static FeatName AttackOfOpportunityForMarshal;
        public static readonly FeatName BackToBack = ModManager.SafelyRegisterEnumMember<FeatName>(
            "BackToBack",
            ["Back to Back"]);
        public static readonly FeatName ToBattle = ModManager.SafelyRegisterEnumMember<FeatName>(
            "ToBattle",
            ["To Battle!"]);
        
        #endregion
        
        #region Blessed One

        public static FeatName BlessedOneDedication;
        public static readonly FeatName BlessedSacrifice = ModManager.SafelyRegisterEnumMember<FeatName>(
            "BlessedSacrifice",
            ["Blessed Sacrifice"]);
        public static FeatName AcceleratingTouchForBlessedOne;
        
        #endregion
        
        #region Scout

        public static FeatName ScoutDedication;
        public static readonly FeatName ScoutsWarning = ModManager.SafelyRegisterEnumMember<FeatName>(
            "ScoutsWarning",
            ["Scout's Warning"]);
        public static readonly FeatName ScoutsCharge = ModManager.SafelyRegisterEnumMember<FeatName>(
            "ScoutsCharge",
            ["Scout's Charge"]);
        public static readonly FeatName TerrainScout = ModManager.SafelyRegisterEnumMember<FeatName>(
            "TerrainScout",
            ["Terrain Scout"]);
        public static readonly FeatName FleetingShadow = ModManager.SafelyRegisterEnumMember<FeatName>(
            "FleetingShadow",
            ["Fleeting Shadow"]);
        public static readonly FeatName ScoutsSpeed = ModManager.SafelyRegisterEnumMember<FeatName>(
            "ScoutsSpeed",
            ["Scout's Speed"]);
        public static readonly FeatName ScoutsPounce = ModManager.SafelyRegisterEnumMember<FeatName>(
            "ScoutsPounce",
            ["Scout's Pounce"]);
        
        #endregion
        
        #region Assassin

        public static FeatName AssassinDedication;
        public static readonly FeatName ExpertBackstabber = ModManager.SafelyRegisterEnumMember<FeatName>(
            "ExpertBackstabber",
            ["Expert Backstabber"]);
        public static FeatName PoisonResistanceForAssassin; // Set later
        public static readonly FeatName SurpriseAttack = ModManager.SafelyRegisterEnumMember<FeatName>(
            "SurpriseAttack",
            ["Surprise Attack"]);
        public static readonly FeatName PoisonWeapon = ModManager.SafelyRegisterEnumMember<FeatName>(
            "PoisonWeapon",
            ["Poison Weapon"]);
        public static FeatName PoisonWeaponForAssassin; // Set later
        public static FeatName SneakAttackerForAssassin; // Set later
        public static readonly FeatName ImprovedPoisonWeapon = ModManager.SafelyRegisterEnumMember<FeatName>(
            "ImprovedPoisonWeapon",
            ["Improved Poison Weapon"]);
        public static FeatName ImprovedPoisonWeaponForAssassin; // Set later
        
        #endregion

        #region Dual-Weapon Warrior

        public static FeatName DualWeaponWarriorDedication;
        public static readonly FeatName DualThrower = ModManager.SafelyRegisterEnumMember<FeatName>(
            "DualThrower",
            ["Dual Thrower"]);
        public static readonly FeatName FlensingSlice = ModManager.SafelyRegisterEnumMember<FeatName>(
            "FlensingSlice",
            ["Flensing Slice"]);

        #endregion

        #region Medic

        public static readonly FeatName DoctorsVisitation = ModManager.SafelyRegisterEnumMember<FeatName>(
            "DoctorsVisitation",
            ["Doctor's Visitation"]);
        public static FeatName TreatConditionSkillVariant;
        public static FeatName HolisticCareSkillVariant;

        #endregion
        
        #region Familiar Master

        public static FeatName FamiliarMasterDedication;
        public static FeatName EnhancedFamiliarForFamiliarMaster;
        public static readonly FeatName OverloadFamiliar = ModManager.SafelyRegisterEnumMember<FeatName>(
            "OverloadFamiliar",
            ["Overload Familiar"]);
        public static readonly FeatName FastCommand = ModManager.SafelyRegisterEnumMember<FeatName>(
            "FastCommand",
            ["Fast Command"]);
        public static readonly FeatName MutableFamiliar = ModManager.SafelyRegisterEnumMember<FeatName>(
            "MutableFamiliar",
            ["Mutable Familiar"]);
        public static readonly FeatName IncredibleFamiliar = ModManager.SafelyRegisterEnumMember<FeatName>(
            "MoreDedications.Archetype.FamiliarMaster.IncredibleFamiliar",
            ["Incredible Familiar"]);
        
        #endregion

        #region Wrestler

        public static readonly FeatName ElbowBreaker = ModManager.SafelyRegisterEnumMember<FeatName>(
            "ElbowBreaker",
            ["Elbow Breaker"]);

        #endregion
        
        #region Bonus Stances
        
        public static readonly FeatName StokedFlameStance = ModManager.SafelyRegisterEnumMember<FeatName>(
            "StokedFlameStance",
            ["Stoked Flame Stance"]);
        public static readonly FeatName InnerFire = ModManager.SafelyRegisterEnumMember<FeatName>(
            "InnerFireSOM",
            ["Inner Fire (SoM)"]);
        public static readonly FeatName WildWindsInitiate = ModManager.SafelyRegisterEnumMember<FeatName>(
            "WildWindsInitiate",
            ["Wild Winds Initiate"]);
        public static readonly FeatName ClingingShadowsInitiate = ModManager.SafelyRegisterEnumMember<FeatName>(
            "ClingingShadowsInitiate",
            ["Clinging Shadows Initiate"]);
        public static readonly FeatName TangledForestStance = ModManager.SafelyRegisterEnumMember<FeatName>(
            "TangledForestStance",
            ["Tangled Forest Stance"]);
        public static readonly FeatName JellyfishStance = ModManager.SafelyRegisterEnumMember<FeatName>(
            "JellyfishStance",
            ["Jellyfish Stance"]);
        
        #endregion
    }

    public static class Illustrations
    {
        public const string MOD_FOLDER = "MoreDedicationsAssets/";
        
        public static readonly Illustration DawnsburySun = new ModdedIllustration(MOD_FOLDER+"PatreonSunTransparent.png");
        public static readonly Illustration CheckSymbol = new ModdedIllustration(MOD_FOLDER+"check symbol.png");
        public static readonly Illustration NoSymbol = new ModdedIllustration(MOD_FOLDER+"no symbol.png");

        #region Martial Artist

        public static readonly Illustration PowderPunchStance = IllustrationName.AlchemistsFire;
        public static readonly Illustration StumblingStance = new ModdedIllustration(MOD_FOLDER+"calabash.png");
        public static readonly Illustration ThunderClap = IllustrationName.ThunderousStrike;
        public static readonly Illustration WildWindsStance = IllustrationName.FourWinds;
        public static readonly Illustration ClingingShadowsStance = IllustrationName.BlackTentacles;

        #endregion

        #region Marshal

        public static readonly Illustration DreadMarshalStance = IllustrationName.HideousLaughter;
        public static readonly Illustration InspiringMarshalStance = IllustrationName.WinningStreak;
        public static readonly Illustration SteelYourself = new ModdedIllustration(MOD_FOLDER+"heartburn.png");
        public static readonly Illustration RallyingCharge = new SideBySideIllustration(IllustrationName.FleetStep, new ModdedIllustration(MOD_FOLDER+"heart-wings.png"));
        public static readonly Illustration ToBattle = new ModdedIllustration(MOD_FOLDER+"flying-flag.png");

        #endregion

        #region Blessed One

        public static readonly Illustration ProtectorsSacrifice = new ModdedIllustration(MOD_FOLDER+"protector's-sacrifice.png");

        #endregion

        #region Dual-Weapon Warrior

        public static readonly Illustration FlensingSlice = new ModdedIllustration(MOD_FOLDER+"FlensingSlice.png");

        #endregion
    }
    
    public static class PersistentActions
    {
        public const string PoisonWeaponCharge = "PoisonWeaponCharge";
        public const string OverloadFamiliar = "OverloadFamiliar";
        public const string FastCommand = "FastCommand";
    }
    
    public static class QEffectIds
    {
        // Bastion
        public static QEffectId NimbleShieldHand;
        
        // Martial Artist
        public static QEffectId PowderPunchStance;
        public static QEffectId StumblingStance;
        public static QEffectId TigerStance;
        public static QEffectId FlatFootedToStumblingFeint;
        
        // Marshal
        public static QEffectId MarshalsAuraProvider;
        public static QEffectId MarshalsAuraEffect;
        public static QEffectId DreadMarshalStance;
        public static QEffectId InspiringMarshalStance;
        
        // Assassin
        public static QEffectId MarkForDeathCaster;
        public static QEffectId MarkForDeathTarget;
        public static QEffectId ExpertBackstabber;
        
        // Dual-Weapon Warrior
        public static QEffectId FlenseCounter;
        public static QEffectId FlenseWeapons;
        
        // Bonus stances
        public static QEffectId StokedFlameStance;
        public static QEffectId WildWindsStance;
        public static QEffectId ClingingShadowsStance;
        public static QEffectId TangledForestStance;
        public static QEffectId JellyfishStance;
        
        // Misc
        public static QEffectId GreaterScoutActivity;
        
        public static void Initialize()
        {
            // Bastion
            NimbleShieldHand = ModManager.SafelyRegisterEnumMember<QEffectId>("NimbleShieldHand");
            
            // Martial Artist
            PowderPunchStance = ModManager.SafelyRegisterEnumMember<QEffectId>("Powder Punch Stance");
            StumblingStance = ModManager.SafelyRegisterEnumMember<QEffectId>("Stumbling Stance");
            TigerStance = ModManager.SafelyRegisterEnumMember<QEffectId>("Tiger Stance");
            FlatFootedToStumblingFeint = ModManager.SafelyRegisterEnumMember<QEffectId>("FlatFootedToStumblingFeint");
            
            // Marshal
            MarshalsAuraProvider = ModManager.SafelyRegisterEnumMember<QEffectId>("MarshalsAuraProvider");
            MarshalsAuraEffect = ModManager.SafelyRegisterEnumMember<QEffectId>("Marshal's Aura");
            DreadMarshalStance = ModManager.SafelyRegisterEnumMember<QEffectId>("Dread Marshal Stance");
            InspiringMarshalStance = ModManager.SafelyRegisterEnumMember<QEffectId>("Inspiring Marshal Stance");
            
            // Assassin
            MarkForDeathCaster = ModManager.SafelyRegisterEnumMember<QEffectId>("MarkForDeathCaster");
            MarkForDeathTarget = ModManager.SafelyRegisterEnumMember<QEffectId>("MarkForDeathTarget");
            ExpertBackstabber = ModManager.SafelyRegisterEnumMember<QEffectId>("ExpertBackstabber");
            
            // Dual-Weapon Warrior
            FlenseCounter = ModManager.SafelyRegisterEnumMember<QEffectId>("FlenseCounter");
            FlenseWeapons = ModManager.SafelyRegisterEnumMember<QEffectId>("FlenseWeapons");
            
            // Bonus stances
            StokedFlameStance = ModManager.SafelyRegisterEnumMember<QEffectId>("Stoked Flame Stance");
            WildWindsStance = ModManager.SafelyRegisterEnumMember<QEffectId>("Wild Winds Stance");
            ClingingShadowsStance = ModManager.SafelyRegisterEnumMember<QEffectId>("Clinging Shadows Stance");
            TangledForestStance = ModManager.SafelyRegisterEnumMember<QEffectId>("Tangled Forest Stance");
            JellyfishStance = ModManager.SafelyRegisterEnumMember<QEffectId>("Jellyfish Stance");
            
            // Misc
            GreaterScoutActivity = ModManager.SafelyRegisterEnumMember<QEffectId>("GreaterScoutActivity");
        }
    }
    
    public static class SpellIds
    {
        #region Martial Artist / Monk

        public static SpellId WildWindsStance { get; set; }
        public static SpellId ClingingShadowsStance { get; set; }

        #endregion

        #region Blessed One

        public static SpellId ProtectorsSacrifice { get; set; }

        #endregion
    }

    public static class Tooltips
    {
        public static readonly Func<string, string> LeveledDC = RegisterTooltipInserter(
            ID_PREPEND + "LevelBasedDC",
            "{b}Level-based DCs{/b}\nWhen a DC is based on your level, it uses one of the following values:\n{b}Level 1:{/b} 15\n{b}Level 2:{/b} 16\n{b}Level 3:{/b} 18\n{b}Level 4:{/b} 19\n{b}Level 5:{/b} 20\n{b}Level 6:{/b} 22\n{b}Level 7:{/b} 23\n{b}Level 8:{/b} 24\n{b}Level 9:{/b} 26");

        public static readonly Func<string, string> InjuryPoison = RegisterTooltipInserter(
            ID_PREPEND + "InjuryPoison",
            """
            {b}Injury Poison{/b}
            {i}(Common item mechanic){/i}
            An injury poison is applied to a weapon that deals piercing or slashing damage, exposing the target of an attack to the poison on a hit.
            
            On a critical miss, the poison wears off and is wasted.
            """);
        
        /// <summary>
        /// Registers a tooltip, then returns a function that can be used to insert the tooltip with any arbitrary text.
        /// </summary>
        /// <param name="tooltipName">The registered name of the tooltip.</param>
        /// <param name="tooltipDescription">The body text of the tooltip.</param>
        /// <returns>(Func[string, string]) A function which takes in the text to insert, and returns a tooltip with the passed text.</returns>
        public static Func<string, string> RegisterTooltipInserter(string tooltipName, string tooltipDescription)
        {
            ModManager.RegisterInlineTooltip(tooltipName, tooltipDescription);
            return input => "{tooltip:" + tooltipName + "}" + input + "{/}";
        }
    }
    
    public static class Traits
    {
        #region Archetypes

        /// <summary>
        /// Mauler archetype
        /// </summary>
        public static readonly Trait Mauler = ModManager.RegisterTrait("Mauler", new TraitProperties("Mauler", true));
        
        /// <summary>
        /// Bastion archetype
        /// </summary>
        public static readonly Trait Bastion = ModManager.RegisterTrait("Bastion", new TraitProperties("Bastion", true));
        
        /// <summary>
        /// Marshal archetype
        /// </summary>
        public static readonly Trait Marshal = ModManager.RegisterTrait("Marshal", new TraitProperties("Marshal", true));
        
        /// <summary>
        /// Blessed One archetype
        /// </summary>
        public static readonly Trait BlessedOne = ModManager.RegisterTrait("BlessedOne", new TraitProperties("Blessed One", true));

        /// <summary>
        /// Scout archetype
        /// </summary>
        public static readonly Trait Scout = ModManager.RegisterTrait("Scout", new TraitProperties("Scout", true));
        
        /// <summary>
        /// Assassin archetype
        /// </summary>
        public static readonly Trait Assassin = ModManager.RegisterTrait("Assassin", new TraitProperties("Assassin", true));
        
        /// <summary>
        /// Dual-Weapon Warrior archetype
        /// </summary>
        public static readonly Trait DualWeaponWarrior = ModManager.RegisterTrait("DualWeaponWarrior", new TraitProperties("Dual-Weapon Warrior", true));
        
        /// <summary>
        /// Familiar Master archetype
        /// </summary>
        public static readonly Trait FamiliarMaster = ModManager.RegisterTrait("FamiliarMaster", new TraitProperties("Familiar Master", true));

        #endregion
        
        // Other traits
        public static readonly Trait Shadow = ModManager.RegisterTrait("Shadow");
    }
}