<Project Sdk="Microsoft.NET.Sdk">
  
  <!-- See the template Directory.Builds.props for additional information -->
  
  <PropertyGroup>
    <!--Modify This For Each Project-->
    <ProjectName>LoresAndWeaknesses</ProjectName>
    
    <AssetsFolder>$(ProjectName)Assets</AssetsFolder>
  </PropertyGroup>
  
  <ItemGroup>
    <Reference Include="New_Skill_Feats_and_Items">
      <HintPath>$(WorkshopInstalls)\3518902782\CustomMods\New Skill Feats and Items.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
  </ItemGroup>
  
  <!-- Asset Folders -->
  <ItemGroup>
    <Assets Include="$(AssetsFolder)\**\*.*"/>
  </ItemGroup>
  
  <Target Name="CopyToGameModsFolder" AfterTargets="Build">
    <!--<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(DawnsburyInstall)\CustomMods"/>-->
    <Copy SourceFiles="$(TargetPath)" DestinationFiles="$(DawnsburyInstall)\CustomMods\0$(TargetName).dll"/>
    <!--<Copy SourceFiles="@(Assets)" DestinationFolder="$(DawnsburyInstall)\CustomMods\$(AssetsFolder)\%(RecursiveDir)"/>-->
    
    <Message Text="Copied to game mod folder." />
  </Target>
  
  <Target Name="CopyToWorkshopUploadable" AfterTargets="Build" Condition=" '$(Configuration)'=='Release' ">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(WorkshopExport)\$(ProjectName)\CustomModsV3"/>
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).pdb" DestinationFolder="$(WorkshopExport)\$(ProjectName)\CustomModsV3"/>
    <Copy SourceFiles="0Harmony.dll" DestinationFolder="$(WorkshopExport)\$(ProjectName)\CustomModsV3"/>
    <Copy SourceFiles="ORC copyright notice.html" DestinationFolder="$(WorkshopExport)\$(ProjectName)" ContinueOnError="true"/>
    <Copy SourceFiles="optional-dependencies.txt" DestinationFolder="$(WorkshopExport)\$(ProjectName)" ContinueOnError="true"/>
    <!--<Copy SourceFiles="@(Assets)" DestinationFolder="$(WorkshopExport)\$(ProjectName)\CustomModsV3\$(AssetsFolder)\%(RecursiveDir)"/>-->
    
    <Message Text="Copied to mod publishing folder." />
  </Target>
  
</Project>

